### ISSUE TITLE
Avoid Druid Broker Bottleneck

### ISSUE THREAD

**Issue by jpullokkaran** [SparklineData/spark-druid-olap#19]
Eliminate broker as bottleneck in cases where large amount of data needs to be pulled out from Druid for subsequent processing in spark. One possible solution is to talk directly to Historical nodes.

For example:
SELECT c_name, 
       bal, 
       sales_prospects_amount 
FROM   (SELECT c_name, 
               Sum(c_acctbal) bal 
        FROM   orderlineitempartsupplier 
        GROUP  BY c_name 
        HAVING Sum(c_acctbal) > 1000)r1 
       JOIN (SELECT cname, 
                    Sum(sales_prospects_amount) AS sales_prospects_amount 
             FROM   sales_leads 
             GROUP  BY c_name) r2 
         ON r1.c_name = r2.cname

**Comment by kainoa21** [comment]
+1

**Comment by hbutani** [comment]
fixed with aae401f45e2d84643d74e076a4ae8042ff0452bd
set queryHistoricalServer = true,
see examples in [HistoricalServerTest](https://github.com/SparklineData/spark-druid-olap/blob/master/src/test/scala/org/sparklinedata/druid/client/HistoricalServerTest.scala)
