### ISSUE TITLE
Using longsum vs count for  queries. 

### ISSUE THREAD

**Issue by sdesikan6** [SparklineData/spark-druid-olap#38]
select date_int, count(*) from MyTable group by date_int order by date_int produces the following JSON
The aggr type should be longsum to get the exact number of rows in the table. 

......
"aggregations" : [ {
      "jsonClass" : "FunctionAggregationSpec",
      "type" : "count",
      "name" : "alias-1",
      "fieldName" : "count"
    } ],

**Comment by hbutani** [comment]
Fixed in b1a16da021206d2aa24700d51d8a07f3e2ba9cb9
