### ISSUE TITLE
Set set spark.sparklinedata.druid.option.numSegmentsPerQuery= 

### ISSUE THREAD

**Issue by sdesikan6** [SparklineData/spark-druid-olap#39]
This option does not seem to change the value for the next run. 

Tried set spark.sparklinedata.druid.option.numSegmentsPerQuery=5 and  set spark.sparklinedata.druid.option.numSegmentsPerQuery="5"

sd

**Comment by hbutani** [comment]
the param name is 'spark.sparklinedata.druid.option.numSegmentsPerHistoricalQuery'
