### ISSUE TITLE
Support regex functions like RLIKE as in the one below.

### ISSUE THREAD

**Issue by sdesikan6** [SparklineData/spark-druid-olap#43]
SELECT `viewability_5`.`campaign_name` AS `campaign_name`, `viewability_5`.`country` AS `country`, `viewability_5`.`creative_size` AS `creative_size` FROM `viewability2`.`viewability_5` `viewability_5` WHERE ((`viewability_5`.`advertiser_name` = 'XXX') AND (CAST(`viewability_5`.`date_string` AS TIMESTAMP) >= CAST('2016-03-01 16:00:00' AS TIMESTAMP)) AND (CAST(`viewability_5`.`date_string` AS TIMESTAMP) <= CAST('2016-03-21 23:59:59' AS TIMESTAMP)) AND LOWER(`viewability_5`.`line_name`) RLIKE CONCAT('.*', 'YYY', '.*')) GROUP BY `viewability_5`.`campaign_name`, `viewability_5`.`country`, `viewability_5`.`creative_size`

**Comment by hbutani** [comment]
done
