### ISSUE TITLE
can we enable druid index on views created by spark data frames?

### ISSUE THREAD

**Issue by chandrasharma28** [SparklineData/spark-druid-olap#48]

**Comment by hbutani** [comment]
Should be fine, as long as the view is registered in the MetaStore Catalog. We call the Metastore to resolve the sourcedataframe of a Druid DataSource.
Haven't tried this, can you post details of your scenario here.

**Comment by chandrasharma28** [comment]
I am trying to create a star schema type join between 5 tables. However, i am hitting an error with the ddl for doing the same. Could you share a syntax or example of the ddl that i could execute through sparkline? 

Here is my scenario, lets consider table1-5 as 5 tables. Table1 is fact table and 4 others are dimension tables. We need to create 4 left joins where table1.a = table2.a and table1.c=table3.c and table1.d=table4.e and table1.e=table5.f. All 5 tables are indexed in druid.

Also, could you share the possibilities of a snow flake type join? For example the output of join between table1 and table 2 is required to create another join with table 3 before the final result is displayed.

**Comment by chandrasharma28** [comment]
Here is the DDL that i am trying to run

CREATE VIEW if not exists druid.View_v1
      USING org.sparklinedata.druid
      OPTIONS (sourceDataframe "analytics.table1,analytics.table2",
      timeDimensionColumn "last_update_date",
      druidDatasource "table1,table2",
      druidHost "zk.hostname",
      zkQualifyDiscoveryNames "true",
      numProcessingThreadsPerHistorical '2',
      starSchema ' {   "factTable" : "druid.View_v1",   
	  			 "relations" : [ { "leftTable": "analytics.table1", "rightTable": "analytics.table2", "relationType": "n-1",
      			 "joinCondition": [ { "leftAttribute": "header_id", "rightAttribute": "header_id" } ] }]  
					}     ')

**Comment by hbutani** [comment]
1. https://github.com/SparklineData/spark-druid-olap/blob/master/src/test/scala/org/sparklinedata/druid/client/StarSchemaMetadataTest.scala has the DDLs for setting up the TPCH snowflake schema.

2. https://github.com/SparklineData/spark-druid-olap/blob/master/src/test/scala/org/sparklinedata/druid/client/JoinTest.scala has sample queries including several TPCH queries.

3. https://github.com/SparklineData/spark-druid-olap/wiki/Defining-a-Star-Schema is a writeup on how to deine a Star Schema and details on restrictions.

**Comment by chandrasharma28** [comment]
Thanks for sharing the materials. However, it doesn't appear to be working as expected.

here is the query that we used for defining our structure:
CREATE TABLE if not exists druid.table_v1
USING org.sparklinedata.druid
OPTIONS (sourceDataframe "analytics.table",
timeDimensionColumn "last_update_date",
druidDatasource "table1",
druidHost "Host1",
zkQualifyDiscoveryNames "true",
starSchema ' { "factTable" : "druid.table_v1", "relations" : [ { "leftTable": "druid.table_v1", "rightTable": "druid.table_v2", "relationType": "n-1", "joinCondition": [ { "leftAttribute": "head_id", "rightAttribute": "header_id" } ] }] } ')

The create query executed successfully but when we ran the explain while querying "druid.table_v1" it only used the druid index for table1. Also, no results were pulled from druid.table_v2. In addition to the, we are unable to run a CREATE VIEW ddl as well.

**Comment by hbutani** [comment]
Can you post all your ddls here. And the query you ran the explain on

**Comment by hegand** [comment]
I am just wondering if the case of starSchema based joins the druid index must be based on  flattened data or not?

I mean: for example we have two tables `table1` and `table2`. 

Columns of `table1`: 

- id1
- col1

Columns of `table2`:

- id2
- fk1
- date
- col2

Where the uniqe path between `table1` and `table2` is `id1` to `fk1`.

What should we do in this case? (Let's asume that `table1` and `table2` are already regisered as a hive table at the metastore)

Flatten the two tables and create index like this:
`{
  "type": "index",
  "spec": {
    "dataSchema": {
      "dataSource": "data",
      "parser": {
        "type": "string",
        "parseSpec": {
          "format": "tsv",
          "timestampSpec": {
            "column": "date",
            "format": "iso"
          },
          "columns": [
            "id1",
            "id2",
            "fk1" ,
            "col1",
            "col2"         ],
          "delimiter": ",",
          "dimensionsSpec": {
            "dimension": [ ],
            "dimensionExclusions": [],
            "spatialDimensions": []
          }
        }
      },
      "metricsSpec": [
        {
          "type": "count",
          "name": "count"
        },
        {
          "type": "doubleSum",
          "name": "col2",
          "fieldName": "col2"
        }
    },
    "ioConfig": {
      "type": "index",
      "firehose": {
        "type": "local",
        "baseDir": "flattened_data",
        "filter": "part*"
      }
    },
    "tuningConfig": {
      "type": "index",
      "partitionsSpec": {
        "type": "hashed",
        "targetPartitionSize": 5000000
      },
      "leaveIntermediate": false,
      "cleanupOnFailure": true,
      "overwriteFiles": false,
      "ignoreInvalidRows": false
    }
  }
}`

And sparkline based table like this:

`CREATE TABLE if not exists table
USING org.sparklinedata.druid
OPTIONS (sourceDataframe "table2",
timeDimensionColumn "date",
druidDatasource "data",
druidHost "Host1",
zkQualifyDiscoveryNames "true",
starSchema ' { "factTable" : "table", "relations" : [ { "leftTable": "table", "rightTable": "table1", "relationType": "n-1", "joinCondition": [ { "leftAttribute": "fk1", "rightAttribute": "id1" } ] }] } ')`

Or create indexes for the two tables separately. Call them table1_idx and table2_idx. And we define the two sparkline table like this:

`CREATE TABLE if not exists table1_d
USING org.sparklinedata.druid
OPTIONS (sourceDataframe "table1",
timeDimensionColumn "date",
druidDatasource "table1_idx",
druidHost "Host1",
zkQualifyDiscoveryNames "true",
starSchema ' { "factTable" : "table1_d", "relations" : [ ] } ')`

`CREATE TABLE if not exists table2_d
USING org.sparklinedata.druid
OPTIONS (sourceDataframe "table2",
timeDimensionColumn "date",
druidDatasource "table2_idx",
druidHost "Host1",
zkQualifyDiscoveryNames "true",
starSchema ' { "factTable" : "table2_d", "relations" : [ { "leftTable": "table2_d", "rightTable": "table1_d", "relationType": "n-1", "joinCondition": [ { "leftAttribute": "fk1", "rightAttribute": "id1" } ] }] } ')`

**Comment by hbutani** [comment]
It's the former. You need to setup 1 druid datasource for each druid index.
In the index spec typically no need to add the dimension table key and foreign key (id1 and fk1); at least no need to add both of them.

**Comment by hegand** [comment]
Thanks for the answer.

I just want to be sure about this: so first I need to flatten the data, build the Druid index, define the sparkline table with starchema def using the original hive table names. Is it the correct way? Thanks in advance for answering.

**Comment by hbutani** [comment]
yes, for the indexing job you have to flatten the star schema. This is typically how an OLAP index is set up. 

FYI: in a future we will be supporting separate indexes for very large dimensions(with cardinality of 10s to 100s of millions)

**Comment by hbutani** [comment]
Regarding the question on views, we support views to the degree Spark SQL does. There are restrictions in Spark SQL for setting up views on top of Spark DataSources, but if your base tables are based on built-in formats views should work.
