### ISSUE TITLE
Filter on decimal data type cause java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by hegand** [SparklineData/spark-druid-olap#49]
Filter on decimal data type cause java.util.NoSuchElementException: None.get error message.

For example: 
`select name, type, count(1) from table where decimal = 10 group by name, type;` -> java.util.NoSuchElementException: None.get error message, but 
`select name, type, count(1) from table where decimal in (10) group by name, type;` -> OK 

This is true for the following operators: `=, >=, <=, >, <`

With Tungsten engine, all of the queries can run without error.

Spark version: 1.6.1

**Comment by hbutani** [comment]
decimal types are not supported(Druid as of 0.9.1 doesn't support bigdecimals, bigdecimals is planned). 
For now we ask users to use double datatype for these columns  in the ddl.

**Comment by hegand** [comment]
Thank you.
