### ISSUE TITLE
Executing same query multiple times and it fetches same result, however new data ingested in druid.

### ISSUE THREAD

**Issue by lssenthilkumar** [SparklineData/spark-druid-olap#50]
Hi Team,

I am executing same query multiple times with same session (same spark context). Also simultaneously new data ingested in druid. I am not getting updated result. Is there a way to clear the cache and fetch updated result from druid.

Finally if I kill the current session and start a new session, then getting updated result.

Let me know if any fix/solution available to this issue.

Thanks,
Senthil

**Comment by hbutani** [comment]
Try issuing a clear druid cache: https://github.com/SparklineData/spark-druid-olap/wiki/Sparkline-SQL-extensions#clear-druid-cache

**Comment by lssenthilkumar** [comment]
No "clear druid cache" is not helping.

First of all its not working in spark-shell, saying can't recognise "clear druid cache".
but in beeline shell using thrift connection, the command works but it gives same result not the updated one.

**Comment by hbutani** [comment]
- yes sparkline sql extensions only work through the thriftserver
- if it is not a druid metadata cache issue, then it is probably something in druid or spark. Doesn't look like a sparkline issue.  Have you turned on caching in druid. Can you check the results on the underlying druid query.

**Comment by lssenthilkumar** [comment]
I used to open multiple shell (new thrift connection) one by one after loading new data into druid.
New shell will give me the updated result but the old shell still same old result (after executing clear cache). Also I just disable the cache in druid and that's also not helping :(.

Did you get the updated result every time with in the same session ??.

**Comment by hbutani** [comment]
Can you check the results on the underlying druid query: issue a execute druid query, for example see https://github.com/SparklineData/spark-druid-olap/wiki/Sparkline-SQL-extensions#execute-any-druid-query

**Comment by lssenthilkumar** [comment]
I executed simple count query, getting different counts between normal query and underlying query.

You can see the difference below. 

0: jdbc:hive2://localhost:10000> clear druid cache;
+---+--+
|   |
+---+--+
|   |
+---+--+
1 row selected (0.041 seconds)
0: jdbc:hive2://localhost:10000> select count(*) from myindex;
+---------+--+
|   _c0   |
+---------+--+
| 133000  |
+---------+--+
1 row selected (0.257 seconds)
0: jdbc:hive2://localhost:10000> on druiddatasource myindex execute query {
0: jdbc:hive2://localhost:10000>   "jsonClass" : "GroupByQuerySpec",
0: jdbc:hive2://localhost:10000>   "queryType": "timeseries",
0: jdbc:hive2://localhost:10000>   "dataSource": "myindex",
0: jdbc:hive2://localhost:10000>   "granularity": "all",
0: jdbc:hive2://localhost:10000>   "aggregations": [
0: jdbc:hive2://localhost:10000>     { "jsonClass" : "FunctionAggregationSpec", "type": "count", "name": "count", "fieldName": "view_time" }
0: jdbc:hive2://localhost:10000>   ],
0: jdbc:hive2://localhost:10000>   "intervals": [ "2016-08-01T00:00:00.000/2016-08-30T00:00:00.000" ]
0: jdbc:hive2://localhost:10000> };
+---------+--+
|  count  |
+---------+--+
| 155000  |
+---------+--+
1 row selected (0.182 seconds)

**Comment by hbutani** [comment]
ok, we are going to try to reproduce this.

**Comment by lssenthilkumar** [comment]
Do you have any update on this ? Would you able to reproduce this ?

**Comment by hbutani** [comment]
Yes I think we can reproduce this. But haven't had the time to look at a fix.

**Comment by hbutani** [comment]
Fixed in commit: 87747e0c896fcf9bf94524c01991e8fb1673fdaf
