### ISSUE TITLE
Is there an option available to use druid index for any kind of queries (including normal select * queries)

### ISSUE THREAD

**Issue by lssenthilkumar** [SparklineData/spark-druid-olap#52]
I have created a spark underlying table and druid data source table. I am planning not to store the raw data for underlying table and looking for an option to use druid index data for all kind queries. Please let me know if you such option to fetch data from druid for all queries.

Currently 'select * from dds_table' query fetching 0 result (Since no raw data stored) and
'select os, count (*) from dds_table group by os' fetching the actual result (fetching from druid).

Please suggest.

**Comment by hbutani** [comment]
this available in the selectquery2 branch. The Druid DataSource Option to enable this is 'nonAggregateQueryHandling'. See examples in [SelectQueryTest](https://github.com/SparklineData/spark-druid-olap/blob/selectquery2/src/test/scala/org/sparklinedata/druid/client/SelectQueryTest.scala)

Plan to make this available in version 0.2.2 by end of the week.
