### ISSUE TITLE
Druid Query Plan not generated when raw dataset is JSON

### ISSUE THREAD

**Issue by pallavi-rao** [SparklineData/spark-druid-olap#53]
I have a raw dataset that contains JSON objects. I'm able to load onto Druid and query it using Druid Queries. However, when, I try to run a "groupBy" command using the accelerator (using 2.0), Druid query plan doesn't get generated, instead, the query runs against raw dataset:
`sql("""CREATE TEMPORARY TABLE click_summary USING org.apache.spark.sql.json OPTIONS (path '/tmp/test/part-r-00000')""".stripMargin).printSchema()
sql("""SELECT count(*) from click_summary""".stripMargin).show()
sql("""
CREATE TEMPORARY TABLE clicksummarized
      USING org.sparklinedata.druid
      OPTIONS (sourceDataframe "click_summary",
      timeDimensionColumn "processingTime",
      druidDatasource "clickenhanced",
      druidHost "localhost",
      zkQualifyDiscoveryNames "true",
            queryHistoricalServers "true",
            numProcessingThreadsPerHistorical '1',
 starSchema ' {   "factTable" : "clicksummarized",   "relations" : []  }     ')""".stripMargin)
sql("""SELECT adIdChain.advertiser_guid, sum(clickCounters.total_click_count) as clicks from clicksummarized group by adIdChain.advertiser_guid""".stripMargin).show()
`

I tried specifying a columnMapping, but that doesn't help either:
With field names in Druid matching the nested naming of JSON
`columnMapping '{"adIdChain.advertiser_guid" : "adIdChain.advertiser_guid","clickCounters.total_click_count" : "clickCounters.total_click_count"}',`

With field names in Druid different from the nested naming of JSON
               `.option("columnMapping", "{\"adIdChain.advertiser_guid\" : \"adIdChain__advertiser_guid\"," +
                        "\"clickCounters.total_click_count\" : \"clickCounters__total_click_count\"}")`

**Comment by pallavi-rao** [comment]
Also, the JSON data is a nested one which is loaded into Druid using the "flattenSpec". 

Explain results in this:
`16/08/22 17:28:27 INFO spark.SparkContext: Created broadcast 3 from toRdd at DruidRelation.scala:124
== Physical Plan ==
TungstenAggregate(key=[adIdChain#9.advertiser_guid#25], functions=[(count(1),mode=Final,isDistinct=false)], output=[advertiser_guid#23,clicks#18L])
+- TungstenExchange hashpartitioning(adIdChain#9.advertiser_guid#25,200), None
   +- TungstenAggregate(key=[adIdChain#9.advertiser_guid AS adIdChain#9.advertiser_guid#25], functions=[(count(1),mode=Partial,isDistinct=false)], output=[adIdChain#9.advertiser_guid#25,count#27L])
      +- Project [adIdChain#9]
         +- Scan DruidRelationInfo(fullName = DruidRelationName(clicksummarized,10.14.114.97,clickenhanced), sourceDFName = click_summary,
timeDimensionCol = processingTime,
options = DruidRelationOptions(1000000,100000,true,true,true,30000,true,/druid,true,true,2147483647,Some(1)))[adIdChain#9,clickCounters#10,eventTime#11L,impression#12,impression_time#13L,misc#14,processingTime#15L,request#16,user#17]
`

**Comment by jpullokkaran** [comment]
Hi Pallavi,

  Could you post the JSON query spec for Druid Scan?

Also is it true that "advertiser_guid" is modeled as dimension and
"total_click_count" is modeled as metric in Druid?

Thanks
John

**Comment by pallavi-rao** [comment]
Thanks @jpullokkaran for the quick response. Yes. advertiser_guid is a dimension and total_click_count is a metric.

Here is the query spec and the results returned:
`$ cat groupBy_query.json 
{
  "queryType": "groupBy",
  "dataSource": "clickenhanced",
  "granularity": "day",
  "dimensions": ["adIdChain__advertiser_guid"],
  "aggregations": [
    { "type": "longSum", "name": "total_click_count", "fieldName": "total_click_count" }
  ],
  "intervals": [ "2016-08-11T06:00:00.000Z/2016-08-11T06:00:00.001Z" ]
}
$ curl -X POST 'localhost:8082/druid/v2/?pretty' -H 'Content-Type:application/json' -d @groupBy_query.json | more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[ {
  "version" : "v1",
  "timestamp" : "2016-08-11T00:00:00.000Z",
  "event" : {
    "total_click_count" : 1,
    "adIdChain__advertiser_guid" : null
  }
}, {
  "version" : "v1",
  "timestamp" : "2016-08-11T00:00:00.000Z",
  "event" : {
    "total_click_count" : 28,
    "adIdChain__advertiser_guid" : "02e0141998ca4758a44f4ffef33e58fb"
  }
}, { .....
`

**Comment by hbutani** [comment]
Sorry for the delay. 
We haven't explicitly looked at supporting nested json data.
I think it is possible to support what you are asking for why the column mapping metadata: could you send us a sample dataset(a few lines would be sufficient) and your druid indexing spec.

**Comment by jpullokkaran** [comment]
Pallavi,

   is the JSON data flattened before loading in to Druid? As was suggested,
 send us sample of this flattened data.

Thanks
John

**Comment by pallavi-rao** [comment]
@jpullokkaran,
Sorry for the delayed response. The data was ingested into Druid using the JSON Flatten spec -> http://druid.io/docs/latest/ingestion/flatten-json.html 

I won't be able to share the data that I ingested due to confidentiality reasons. But, you can ingest a simple address book kinda of data and you should be able to reproduce the problem. If you still need me to send the "address book" spec and data, let me know.

**Comment by hbutani** [comment]
yes please, send us your indexing spec.
