### ISSUE TITLE
Query on the Last segment of a datasource is not returning the expected results

### ISSUE THREAD

**Issue by amitabhsu** [SparklineData/spark-druid-olap#55]
: jdbc:hive2://spl08.dev.dw.sc.gwallet.com:1> explain select count(*) from moat_daily where cast(ts_local as timestamp) >= cast ("2016-08-19 00:00:00Z" as timestamp);
+-----------------------------------------------------------------------------------------------------------------------+--+
|                                                         plan                                                          |
+-----------------------------------------------------------------------------------------------------------------------+--+
| == Physical Plan ==                                                                                                   |
| Project [alias-3#740L AS _c0#739L]                                                                                    |
| +- SortBasedAggregate(key=[], functions=[(sum(alias-3#740L),mode=Complete,isDistinct=false)], output=[alias-3#740L])  |
|    +- ConvertToSafe                                                                                                   |
|       +- TungstenExchange SinglePartition, None                                                                       |
|          +- ConvertToUnsafe                                                                                           |
|             +- Scan DruidQuery(19982889): {                                                                           |
|   "q" : {                                                                                                             |
|     "jsonClass" : "TimeSeriesQuerySpec",                                                                              |
|     "queryType" : "timeseries",                                                                                       |
|     "dataSource" : "moat_daily",                                                                                      |
|     "intervals" : [ "2016-08-19T00:00:00.000Z/2016-08-19T00:00:01.000Z" ],                                            |
|     "granularity" : "all",                                                                                            |
|     "aggregations" : [ {                                                                                              |
|       "jsonClass" : "FunctionAggregationSpec",                                                                        |
|       "type" : "longSum",                                                                                             |
|       "name" : "alias-3",                                                                                             |
|       "fieldName" : "count"                                                                                           |
|     } ]                                                                                                               |
|   },                                                                                                                  |
|   "useSmile" : true,                                                                                                  |
|   "queryHistoricalServer" : true,                                                                                     |
|   "numSegmentsPerQuery" : 2,                                                                                          |
|   "intervalSplits" : [ {                                                                                              |
|     "start" : 1471564800000,                                                                                          |
|     "end" : 1471564801000                                                                                             |
|   } ],                                                                                                                |
|   "outputAttrSpec" : [ {                                                                                              |
|     "exprId" : {                                                                                                      |
|       "id" : 740,                                                                                                     |
|       "jvmId" : { }                                                                                                   |
|     },                                                                                                                |
|     "name" : "alias-3",                                                                                               |
|     "dataType" : { },                                                                                                 |
|     "tf" : "toLong"                                                                                                   |
|   } ]                                                                                                                 |
| }[alias-3#740L]                                                                                                       |
+-----------------------------------------------------------------------------------------------------------------------+--+
37 rows selected (0.049 seconds)

The interval end does not include the last segment (it should be 2016-08-20T00:00:00.000Z)

**Comment by hbutani** [comment]
i think this behavior is correct because all your 2016-08-19 rows have a timestamp of 2016-08-19T00:00:00.000Z
