### ISSUE TITLE
count(distinct(dimension)) cannot translate to hyperUnique

### ISSUE THREAD

**Issue by god0530** [SparklineData/spark-druid-olap#56]
I created a batch ingestion spec and defined a hyperUnique metric in it. When I query data from dataSource using sparkline, I found the count(distinct(dimension)) cannot translate to hyperUnique aggregation. Is it a bug or the misuse I made? or this feature is not supported for now?

**Comment by god0530** [comment]
The druid cardinality aggregator is not supported too, as supplementary.

**Comment by jpullokkaran** [comment]
We haven't added support for cardinality or HyperUnique aggregator.
We should be adding support for it soon.

Thanks

**Comment by hbutani** [comment]
See the thread on this in google groups: https://groups.google.com/forum/#!topic/sparklinedata/sRCdIO1gzKM

**Comment by god0530** [comment]
https://groups.google.com/forum/#!topic/sparklinedata/sRCdIO1gzKM
This post is mine.....
I have implemented hyperUnique in sparklinedata，can I make a PR？

**Comment by hbutani** [comment]
oh sorry didn't realize this
yes of course please send us a PR

**Comment by hbutani** [comment]
closing the issue, but a PR is very welcome

**Comment by god0530** [comment]
Copy. I will send the PR ASAP.
