### ISSUE TITLE
Using spark-druid-olap in an external project

### ISSUE THREAD

**Issue by JithinThomas** [SparklineData/spark-druid-olap#57]
I couldn't find documentation on how to use this custom DataSource implementation and optimizations in an external project. 

(a) Is the jar file published to an external repo such that it can be referred to via the build.sbt file in my project?

OR

(b) Do I need to clone the repo and manually build the jar myself?

Thanks,
Jithin

**Comment by hbutani** [comment]
Download jar from http://search.maven.org/remotecontent?filepath=com/sparklinedata/spl-accelerator_2.10/0.3.0/spl-accelerator_2.10-0.3.0-assembly.jar

To turn on the Sparkline Planner issue
```scala
org.apache.spark.sql.sources.druid.DruidPlanner(sqlContext)
```
in your Spark App.
