### ISSUE TITLE
query druid table which update per 1 min

### ISSUE THREAD

**Issue by exitNA** [SparklineData/spark-druid-olap#62]
hi:
   i have a table which update per 1 min, and i found that the spark druid olap doesn't update with the datasource.
for example:
select ts, count(*) from test_table where ts > '2016-12-06T19:25+08:00' group by ts;
the result always is:
+----------------------+-----------+--+
|          ts          | count(1)  |
+----------------------+-----------+--+
| 2016-12-06 19:26:00  | 16546     |
| 2016-12-06 19:27:00  | 16948     |
+----------------------+-----------+--+
but the datasource's ts is far away from '2016-12-06 19:27:00'

**Comment by hbutani** [comment]
Which version are you using? 
There is a fix with caching DruidDS in trunk: a65dc87484db2ddcbd65d930743853c457680365

**Comment by exitNA** [comment]
i use master branch, git 7f2885593821e5234864a1c187bf7b3ed9346a28.

**Comment by hbutani** [comment]
Can you issue a 'clear druid cache' sql statement and then try your query.
[clear druid cache](https://github.com/SparklineData/spark-druid-olap/wiki/Sparkline-SQL-extensions#clear-druid-cache), should cause our layer to reread all Druid metadata.

If you set logLevel to INFO, you should also see the metadata query we issue to Druid to get all the segments from the coordinator. If invoking 'clear druid cache' doesn't fix the issue than can you find this Druid Query from the log and issue against the Druid Coordinator(using Postman or ur favorite json tool)

**Comment by hbutani** [comment]
BTW, in SQL you can issue queries against the [Druid Segments View](https://github.com/SparklineData/spark-druid-olap/wiki/Runtime-Views#ddruidsegments-view) to see what Druid segments are seen by our layer.

**Comment by exitNA** [comment]
hi:
issue "clear druid cache;", i got 
`Error: java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/command/RunnableCommand$class (state=,code=0)`

**Comment by hbutani** [comment]
Just tried 'clear druid cache', I cannot reproduce the error.
I deployed the assembly jar on spark-2.0.1 cluster running in standalone mode.

Several examples on Sparkline SQL extensions in [SparklineSQLTest](https://github.com/SparklineData/spark-druid-olap/blob/master/src/test/scala/org/sparklinedata/druid/client/test/SparklineSQLTest.scala)
In your sql client just issue them as regular sql commands.

Can you send me the full stacktrace of your error.

**Comment by exitNA** [comment]
sorry, the console just print only one message 'Error: java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/command/RunnableCommand$class (state=,code=0)', and no job log about this opt, i use spark-2.0.2-bin-hadoop2.7 standalone mode, but build spark-druid-olap with spark 2.0.1 git 7f2885593821e5234864a1c187bf7b3ed9346a28

**Comment by hbutani** [comment]
Not much here to help debug this. Can you email me your thriftserver log?
