### ISSUE TITLE
Spark-druid-olap

### ISSUE THREAD

**Issue by ArslanSaleem** [SparklineData/spark-druid-olap#64]
Hi, 
I am working to build spark-druid-olap to use for spark 2.0 and scala 2.11.8. Currently what i had done is that i cloned the repository and and trying build using.

`sbt run build.sbt`

But i am facing issue related to some missing artifacts. Following is the issue that i am facing. 

`sbt.ResolveException: unresolved dependency: com.sparklinedata#sp-mdformat_2.11;0.0.1: not found
`

**Comment by hbutani** [comment]
We will be launching a private beta of the next version shortly. Please contact us at info@sparklinedata.com. If you are looking for previous version see the [Releases](https://github.com/SparklineData/spark-druid-olap/releases) page.

**Comment by ArslanSaleem** [comment]
Thanks hbutani.
