### ISSUE TITLE
where does olap translate sql to dq string

### ISSUE THREAD

**Issue by dannyhnu** [SparklineData/spark-druid-olap#68]
#This is not a issue, just ask for help
When I use Spark sqlContext instead of SparklineDataContext, I found DefaultSource create a null DruidQuery by 
val dQuery = parameters.get(DRUID_QUERY).map { s =>
      parse(s).extract[DruidQuery]
}
Is this because DruidStrategy did not register to spark session?
Is there any way I load all SparklineDataModule without create a SparklineDataContext?
Thanks!

**Comment by hbutani** [comment]
try https://github.com/SparklineData/snapshell if you drop this jar in the SNAP folder it should enable the enhanced optimizers and parser

**Comment by amoussoubaruch** [comment]
HI @dannyhnu 

I have problem to start sparklinedatathriftserver. I follow all step for connect spark to druid but it did'nt work. 
How are you configure that please? 

Thanks

**Comment by dannyhnu** [comment]
@amoussoubaruch  sorry I didn't start a sparklinedatathriftserver. In my case, I just need spark executor to call druid broker. So I use Spark sqlContext instead of SparklineDataContext

**Comment by amoussoubaruch** [comment]
ok thanks much!
