### ISSUE TITLE
Can't connect to jdbc:hive2://localhost:10000

### ISSUE THREAD

**Issue by amoussoubaruch** [SparklineData/spark-druid-olap#70]
Hi,

I'm trying to test your solution to query druid with spark but i have one problem. 

I successfully launch spark thriftserver and when i try to connect to bin/beeline with this command i got this error :

Enter password for jdbc:hive2://localhost:10000: 
17/09/08 10:13:05 INFO jdbc.Utils: Supplied authorities: localhost:10000
17/09/08 10:13:05 INFO jdbc.Utils: Resolved authority: localhost:10000
17/09/08 10:13:06 INFO jdbc.HiveConnection: Will try to open client transport with JDBC Uri: jdbc:hive2://localhost:10000
17/09/08 10:13:06 INFO jdbc.HiveConnection: Could not open client transport with JDBC Uri: jdbc:hive2://localhost:10000
17/09/08 10:13:06 INFO jdbc.HiveConnection: Transport Used for JDBC connection: null
Error: Could not open client transport with JDBC Uri: jdbc:hive2://localhost:10000: java.net.ConnectException: Connection refused (state=08S01,code=0)

Can you please tell me what is happen? 

Thanks for any reply.

**Comment by hbutani** [comment]
check the thriftserver logs; looks like the thriftserver didn't start

**Comment by amoussoubaruch** [comment]
Ok

**Comment by amoussoubaruch** [comment]
@hbutani 

thriftserver don't start. This my log ::



Spark Command: /usr/lib/jvm/jre-1.8.0-openjdk/bin/java -cp /opt/spark/conf/:/opt/spark/jars/*:/opt/hadoop/etc/hadoop/:/opt/hadoop/etc/hadoop/ -Xmx24g org.apache.spark.deploy.SparkSubmit --class org.apache.spark.sql.hive.thriftserver.sparklinedata.HiveThriftServer2 --packages com.databricks:spark-csv_2.10:1.1.0,SparklineData:spark-datetime:0.0.2 --jars /root/binaries/dep/druid-olap/spl-accel-assembly-0.4.1.jar spark-internal
========================================
Warning: Ignoring non-spark config property: master=yarn
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
:: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.10 added as a dependency
SparklineData#spark-datetime added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]


I am using druid 10 and spark 2.10. I don't know if the lasted version of spark-druid-olap is build for this version.

**Comment by hbutani** [comment]
Yes, as you can see in in [build.sbt](https://github.com/SparklineData/spark-druid-olap/blob/master/build.sbt) the last version we updated to is Spark 2.0.2 and Druid 0.9.1

Depending on your usecase consider trying out our [SNAP Platform](http://sparklinedata.com/sparkline-snap-olap-on-spark/)
