### ISSUE TITLE
Is this project alive? Does it support Spark 2.3.x/2.4.x?

### ISSUE THREAD

**Issue by LiShuMing** [SparklineData/spark-druid-olap#71]

**Comment by hbutani** [comment]
No, we graduated this into the SNAP product 3 years back.
Our company Sparklinedata was bought by Oracle: https://www.oracle.com/corporate/acquisitions/sparklinedata/ 
SNAP is available on Spark 2.3 and 2.4

**Comment by LiShuMing** [comment]
Thanks for @hbutani 's replies. Understand.
